DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwaXJlcyI6MTcyODY4Njg5NCwidXNlcklEIjoyfQ.lazBRzZ4rU2jBZsb365-TOMhMypUpHAk-dFoHJ1KzuI