POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHBpcmVzIjoxNzI4Njg2ODI5LCJ1c2VySUQiOjF9.NJqKx1Suqag8o3Ji_rjlJfV5M0TvdYsmlUXaHd2x5Rc

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2024-10-09T15:30:00.000Z"
}
