DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHBpcmVzIjoxNzI4NjgzOTkxLCJ1c2VySUQiOjF9.Ym0iDySP1RtWUFDIR_rAJjENB6W0iT2LzAb3p-9mgdg