DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwaXJlcyI6MTcyODY4MzQ0NCwidXNlcklEIjoyfQ.rVsjippXxq-3kq6lPawsJ2ZohWhvEbmnzLka7O4L_Gs